import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebarsAscii: SidebarsConfig = {
    tutorialSidebar: [
        { type: "autogenerated", dirName: "." }, // Keeps your automatic doc structure
    ],
};

export default sidebarsAscii;
