import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebarsDataviz: SidebarsConfig = {
    tutorialSidebar: [
        { type: "autogenerated", dirName: "." }, // Keeps your automatic doc structure
    ],
};

export default sidebarsDataviz;
